model_config: Models/LibriTTS/config.yml
checkpoint: Models/LibriTTS/epochs_2nd_00020.pth
root_path: /store/store2/data
split: val
text_list: Data/mini_val_list_esd.txt
ref_list: Data/mini_ref_val_list_esd.txt
output_dir: Models/zeroshot/samples
device: cpu

sample_rate: 24000
alpha: 0.3
beta: 0.7
diffusion_steps: 5
embedding_scale: 1.0
seed: 0
